---
title: "ARBEIDSKRAV 4"
author: "Jacob Mollatt"
date: "11-11-2021"
output:
  html_document:
    df_print: paged
  word_document:
    reference_docx: resources/template.docx
  pdf_document: default
bibliography: resources/references.bib
csl: resources/vancouver.csl
---

# Studiedesign

## Formål

Forfatterne i samtlige studier inkludert i denne oppgaven ønsker å bidra til økt kunnskap som kan være med å løse den økende utfordringen med hamstringsskader i idretten, ettersom denne utfordringen har store konsekvenser for både prestasjon og økonomi [@ekstrand2011; @hickey2014; @eirale2013; @hickey2020; @askling2014; @hamilton2015; @ahamid2014; @askling2013]. Forfatterne ønsker å bidra til en økt kunnskap gjennom å formulere ulike spørsmål og sammenligningsgrunnlag. Alle studier har som formål å sammenligne to eller flere ulike rehabiliteringsprotokoller for å se hvilken av disse som har best effekt på tid til retur til idrett. Mer spesifikt ønsker tre av studiene å sammenligne hvilken effekt to ulike typer aktive rehabiliteringsprotokoller har på tiden det tar for å returnere til idrett etter en akutt hamstringsskade[@askling2014, @askling2013, @hickey2020]. De to andre studiene forsøker å se hvilken effekt injeksjoner av Platelet-Rich-Plasma (PRP) har på rehabiliteringen av en hamstringsskade når det kombineres med aktiv rehabilitering, målt gjennom tid til retur til idrett[@ahamid2014; @hamilton2015].

Den røde tråden i disse artiklene finner vi igjen i utgangspunktet samtlige forfattere har i den tydelige byrden hamstringsskader har på prestasjon og økonomi i toppidretten[@ekstrand2011; @hickey2014; @eirale2013]. Videre vil kunnskapen vi allerede har, og dagens praksis omkring rehabiliteringen av hamstringsskader være med å påvirke retningen på disse studiene [@brooks2006; @horst2017; @opar2012; @podlog2014]. Økt kunnskap leder ofte til økt nysgjerrighet, og tiltak for å ytterlige optimalisere denne rehabiliteringsprosessen vil potensielt kunne gi tydelige fortrinn i toppidretten på flere ulike måter, hvor prestasjon og økonomi skiller seg ut som de to store.

## Metodisk sammenligning

Detaljert karakteristikk i metoden til de ulike studiene inkludert finnes i Tabell 1.

Alle de fem inkluderte artiklene er designet som randomiserte kontrollerte studier(RCT)[@askling2014; @askling2013; @hickey2020; @ahamid2014; @hamilton2015].En RCT er et forskningsstudie som sammenligner to eller flere forskjellige grupper[@hulley2013, s 137-139.]. Ofte mottar en av gruppene en form for intervensjon man ønsker å undersøke, samtidig som den andre gruppen mottar enten ingen intervensjon, eller en annen form for intervensjon. Gruppen som ikke mottar en intervensjon, eller eventuelt en placebointervensjon, kalles ofte kontrollgruppe. Intervensjonen varierer fra fagfelt til fagfelt, men er ofte en form for behandling, trening, medisinering eller lignende. Målet med en RCT er å sammenligne utfallet en intervensjon har på én gruppe, opp mot utfallet i en annen gruppe som enten mottok ingen intervensjon eller en annen type intervensjon. På denne måten ønsker man i gjennom et RCT-design å trekke slutninger om sammenhenger mellom årsak og effekt[@hulley2017, s. 121]. I slike studier er ofte blinding av deltakere og forskningspersoner, samt randomisering av gruppene to hjørnesteiner for å i større grad kunne oppnå disse målene om inferens[@hulley2017, s.138-140].

Dette er et studiedesign som ligger høyt på evidenspyramiden, og i mindre grad er utsatt for bias og konfundering sammenlignet med andre type design som for eksempel case-control design og cohortdesign[@hulley2017, s.109-110]. Samtidig er dette også et studiedesign som er mer kostbart og tidkrevende, i tillegg til at studiedesignet muligens krever mer detaljplanlegging og omfattende arbeid rundt speiselt randomisering og blinding [@hulley2017, s.139-141]. Det er også enkelte fagfelt eller forskningsområder der en blinding av deltakerne, en placebo-kontroll, eller blinding av forskningspersoner ikke alltid er mulig å gjennomføre, slik som for eksempel trening, manuell behandling, ortopedi, psykiatri eller lignende. Derfor vil man ofte kunne se sammenligninger av to intervensjoner, fremfor sammenligning mot en kontroll[@hulley2017, s.137-139].

Deltakerne i studiene er hentet fra en populasjon av voksne idrettsutøvere med akutte hamstringsskader. Tretten ulike idretter er representert, med fotball og friidrett som de to største. Utvalgsstørrelsen varierte fra 24 til 90, med et snitt på 62 deltakere over de fem studiene. Totalt var det 308 deltakere, kjønnsfordelingen var omtrent 9% kvinner og 91% menn. To av studiene hadde kun mannlige deltakere [@hickey2020; @hamilton2015].Tre av studiene hadde på forhånd gjort en utregning av ønsket utvalgsstørrelse for en statistisk styrke på 80% [@hickey2020; @ahamid2014; @hamilton2015].

Statistisk styrke er et mål på sannsynligheten forskeren har for å finne en statistisk signifikans forskjell dersom det finnes en reell forskjell i populasjonon[@jones2004,@turner2018]. Det vil si at dersom forfatterne har klart å oppnå den ønskede utvalgsstørrelsen, vil de ha 80% sannsynlighet for å oppdage en statistisk signifikant forskjell mellom de ulike rehabiliteringsmetodene de undersøker, dersom den effekten er reell. Dette påvirkes også av angitt p-verdi, som sier oss noe om hvor ofte vi kan tillate oss å finne en forskjell mellom gruppene ved en tilfeldighet. Med p-verdi satt til 0.05, vil det si at vi godtar å trekke slutning om at det er en forskjell, når det i realiteten ikke er det (falsk positiv), i 5% av tilfellene

Alle studiene sammenlignet ulike rehabiliteringsmetoder av akutte hamstringsskader opp mot hverandre med retur til idrett som utfallsmål, med mål om å finne forskjeller i utfallet av de ulike rehabiliteringsmetodene. Retur til idrett var definert ulikt i flere av studiene, og inklusjonskriteriene varierte også i stor grad mellom studiene. Dette gjør det vanskeligere å sammenligne resultatene fra studiene opp mot hverandre.

```{r eval=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
Tabell1 <- read_excel("resources/Tabell.xlsx")
```

**Tabell 1 Studiekarakteristikk**

+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Forfatter      | Utvalg                                                           | Rekruttering                                                                                                                                                                                                                                                                                                       | Statistisk styrke                                                                                                         | Intervensjoner                                                                                                                                                                           | Utfallsmål                                                                                                                                    |
+:===============+:=================================================================+:===================================================================================================================================================================================================================================================================================================================+:==========================================================================================================================+:=========================================================================================================================================================================================+:==============================================================================================================================================+
| Hickey, 2020   | 45 menn med akutt HSI\* \<7 dager.                               | Rekruttering skjedde løpende over en periode på 15mnd. Potensielle deltakere ble rekruttert via reklameplakater og kontakt med lokale idrettslag og klinikker. Deltakere ble til slutt inkludert på bakgrunn av forhåndsdefinerte inklusjonskriterier.                                                             | 29 deltakere var ønsket for statistisk styrke på 80%, medregnet en drop-out på 20%. Basert på en effektstørrelse på 1,2.  | Progressiv steg vis rehabiliteringsprotokoll bestående av øvelser for å styrke hamstringmuskulatur og løping. Progresjon og gjennomføring innenfor smertefrihet. 0 på NRS\*\*            | Tid til retur. Tid fra skadetidspunkt til kriterier for retur til idrett var bestått.                                                         |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           | Progressiv stegvis rehabiliteringsprotokoll bestående av øvelser for å styrke hamstringmuskulatur og løping.Progres jon og gjennomføring innenfor en gitt smertegrense \<4 på NRS\*\*.   |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           |                                                                                                                                                                                          |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           |                                                                                                                                                                                          |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Askling, 2013  | 75 fotballspillere med akutt HSI\* \<2 dager.                    | Rekrutteringen skjedde over en løpende periode på 33 måneder. Gjennom forfatternes idrettmedisinske kontaktnettverk innen svensk fotball. Deltakere ble til slutt inkludert på bakgrunn av forhåndsdefinerte inklusjonskrit erier.                                                                                 | Ikke definert                                                                                                             | Rehabiliteringsprotokoll bestående av 3 øvelser med fokus på å styrke hamstringen i hovedsak med eksentrisk muskelarbeid (L-protokoll).                                                  | Tid til retur. Tid fra skadetidspunkt til full deltakelse i lagstrening og tilgjengelighet for kamp.                                          |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           | Rehabiliteringsprotokoll bestående av 3 øvelser med fokus på å styrke hamstringen (C-protokoll).                                                                                         |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Askling, 2014  | 57 elite friidrettsutøvere med akutt HSI\* \<2 dager.            | Rekrutteringen skjedde over en løpende periode på 38 måneder. Gjennom forfatternes idrettmedisinske kontakt nettverk innen svensk friidrett, og invitasjoner ble også sendt ut gjennom det svenske friidrettsforbundet. Deltakere ble til slutt inkludert på bakgrunn av forhåndsdefinerte inklusjonskrit erier.   | Ikke definert                                                                                                             | Rehabiliteringsprotokoll bestående av 3 øvelser med fokus på å styrke hamstringen i hovedsak med eksentrisk muskelarbeid (L-protokoll).                                                  | Tid til retur. Tid fra skadetidspunkt til full deltakelse i trening.                                                                          |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           | Rehabiliteringsprotokoll bestående av 3 øvelser med fokus på å styrke hamstringen (C-protokoll).                                                                                         |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Hamid, 2014    | 24 Ikke-profe sjonelle utøvere med akutt HSI\* \<7 dager         | Pasienter over 18 år som oppsøkte forfatternes Idrettsmedisinske klinikk med mistenkt hamstringsskade ble undersøkt og inkludert etter diagnose og på bakgrunn av forhåndsdefinerte inklusjonskri terier.                                                                                                          | 28 deltakere (14 i hver intervensjons-gruppe) var ønsket for statistisk styrke på 80% med signifikansnivå satt til 0,05.  | Rehabiliterings protokoll for å styrke hamstring samt progressiv agilitytrening og styrke av kjernemuskulatur. Samt injeksjon av PRP \*\*\*.                                             | Tid til retur. Tid fra skadetidspunkt til kriterier for retur til idrett var oppfylt. Målt ukentlig eller til studien ble avsluttet(16 uker). |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           | Rehabiliterings protokoll for å styrke hamstring samt progressiv agilitytrening og styrke av kjernemuskulatur.                                                                           |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Hamilton, 2015 | 90 Idrettsutøvere henvist til ASPETAR med akutt HSI\* \<5 dager. | Pasienter ble rekruttert fra klubber og forbund tilknyttet et nasjonalt idrettsmedisinsk program i Qatar.Medisinsk støtteapparat henviste til studiesenteret ved mistanke om en akutt HSI. Deltakerne ble inkludert på bakgrunn av forhåndsdefinerte inklusjonskri terier.                                         | 60 deltakere var ønsket for statistisk styrke på 80% med signifikansnivå på 0,05 medregnet en drop-out på 10%.            | Rehabiliterings protokoll for å styrke hamstring (usual care), samt injeksjon av PRP\*\*\*                                                                                               | Tid til retur. Tid fra skadetidspunkt til gjennomført rehabilitering og kriterier for retur til idrett var oppfylt.                           |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           | Rehabiliterings protokoll for å styrke hamstring (usual care), samt injeksjon av placebosammenligner(PPP \*\*\*\*)                                                                       |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                  |                                                                                                                                                                                                                                                                                                                    |                                                                                                                           | Rehabiliteringsprotokoll for å styrke hamstring (usual care),                                                                                                                            |                                                                                                                                               |
+----------------+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+

: *\*Hamstring strain injury - hamstringsskade\
\*\*Numerical Rating Scale**\
***\*\*\*Platelet-Rich-Plasma\
\*\*\*\*Platelet-Poor-Plasma\

### Statistiske analyser.

Alle studiene brukte en statistisk analyse med mål om å se på intervensjonens effekt på hovedutfallsmålet, som var tid til retur til idrett. To studier benyttet seg av Mann-Withney U test for å undersøke dette [@askling2013, @askling2014]. Dette er en ikke-paramtetrisk test som kan brukes for å undersøke om det er en forskjell i en avhengig variabel mellom to uavhengige grupper. I dette tilfellet var den avhengige variablen tid til retur til idrett, og de uavhengige gruppene de to intervensjonsgruppene som fulgte L-protokoll eller C-protokoll[@askling2013, @askling2014]. De tre andre studiene så på kumulativ survival rate og tid til retur til idrett gjennom å bruke Kaplan-Meier survival analyse [@hickey2020, @ahamid2014, @hamilton2015]. Dette er en analyse som er ment å sammenligne om det er en statistisk forskjell i sannsynlighetsberegningen for tid til retur til i drett mellom de ulike intervensjonsgruppene[@goel2010,@fink2006]. Dette på tross av at det kan argumenteres for at man heller burde bruke andre analyser innen idrettsmedisin, som for eksempel time-to-event analysis [@nielsen2018, @akram2016]. De samme tre studiene brukte også en Cox-regresjonsmodell for å se på de ulike intervensjoners effekt på hovedutfallsmålet, som var tid til retur til idrett[@hickey2020, @ahamid2014, @hamilton2015].

## Resultater

I studiene som sammenlignet to ulike aktive rehabiliteringsprotokoller fant to av studiene signifikante forskjeller i tid til retur til idrett [@askling2013, @askling2014]. Den tredje av studiene fant ingen signifikant forskjell i tid til retur til idrett[@hickey2020]. Blant de to studiene som undersøkte effekten av en PRP injeksjon, fant den ene studien en signifikant kortere tid til retur til idrett i gruppen med PRP injeksjon og standard rehabilitering, sammenlignet med gruppen som kun gjennomgikk standard rehabilitering[@ahamid2014]. Den andre studien fant ingen signifikant forskjell i tiden til retur til idrett mellom gruppen som mottok PRP-injeksjon og gruppen som mottok en standard rehabilitering[@hamilton2015]. Resultatene er oppsummert fordelt på studiene under.

#### Hickey, 2020 [@hickey2020]

Ingen signifikant forskjell i hovedutfallsmål, som var tid til retur til idrett. Sekundære utfallsmål på isometrisk knefleksjon og fasikkellengde i biceps femoris caput longum var bedre i gruppen med rehabilitering innenfor smertegrense 4 på Numerical Rating Scale(NRS). Median tid fra skade til retur til idrett var 15 dager(95% konfidensintervall) i gruppen med smertefrihet, og 17 dager(95% konfidensintervall) i gruppen med smertegrense på 4 på NRS. P-verdi på 0.37.

#### Askling, 2013 [@askling2013]

Signifikant kortere rehabilitering i gruppen med eksentrisk muskelarbeid og forlenging av muskulatur(L-protokoll) sammenlignet med den andre konvensjonelle rehabiliteringsgruppen(C-protokoll)(p\<0.001). Gjennomsnittlig tid til til retur til idrett i L-protokoll var 28 dager (1SD±15, range 8-58 dager), sammenlignet med et snitt på 51 dager (1SD±21, range 12-94 dager) i C-protokoll.

#### Askling, 2014 [@askling2014]

Signifikant kortere rehabilitering i gruppen med eksentrisk muskelarbeid og forlenging av muskulatur(L-protokoll) sammenlignet med den andre konvensjonelle rehabiliteringsgruppen(C-protokoll)(p\<0.001, d=−1.21). Gjennomsnittlig tid til retur til idrett i L-protokoll var 49 dager (1SD±26, range 18--107 dager), sammenlignet med et snitt på 86 dager (1SD±34, range 26--140 dager) i C-protokoll.

#### Hamid, 2014 [@ahamid2014]

Pasientene som mottok PRP injeksjon sammen med rehabiliteringsprogrammet hadde en signifikant tidligere retur til idrett sammenlignet med de som ikke mottok PRP-injeksjon(p = 0.02). Gjennomsnittlig tid til retur var 42.5±20.6 dager i kontrollgrupen, og 26.7±7 dager i PRP gruppen.

#### Hamilton,2015 [@hamilton2015]

Justert differanse i tid til retur til idrett mellom PRP-gruppen og PPP-gruppen var −5.7 dager (95% CI, p=0.01). Mellom PRP og kontrollgruppen −2.9 dager (95% CI, p=0.189) og mellom PPP og kontrollgruppen 2.8 dager (95% CI, p=0.210).

## Konklusjoner

Tre av studiene konkluderte med at de fant en forskjell i effekten de ulike intervensjonene de undersøkte hadde på tid til retur til idrett[@askling2013; @askling2014; @ahamid2014]. To av disse studiene konkluderte med at en rehabiliteringsprotokoll med eksentrisk muskelarbeid og overvekt av forlenging av muskulatur i muskelarbeidet er mer effektivt en konvensjonelle rehabiliteringsøvelser[@askling2013, @askling2014]. Den siste studien konkluderte med at en PRP-injeksjon kombinert med standard rehabilitering hadde større positiv effekt på tid til retur til idrett enn en standard rehabilitering alene[@ahamid2014]. De to siste studiene konkluderte med at det ikke var noen forskjell i effekten de ulike intervensjonene de undersøkte hadde på tid til retur til idrett[@hickey2020, @hamilton2015]. To av studiene inkludert kom til motsvarende konklusjoner, der den ene konkluderte med at en enkelt PRP-injeksjon ikke hadde effekt på tid til retur til idrett, mens den andre konkluderte med at en enkelt PRP-injeksjon hadde positiv effekt på tid til retur til idrett[@hamilton2015, @ahamid2014]. Konklusjoner er oppsummert og fordelt på de ulike studiene under.

#### Hickey, 2020 [@hickey2020]

Rehabilitering innenfor smertegrense på 4 på NRS ga ingen raskere retur til idrett enn rehabilitering innenfor smertefrihet, men bedret andre utfallsmål som isometrisk styrke i knefleksjon og fasikkellengde.

#### Askling, 2013 [@askling2013]

En rehabiliteringsprotokoll med eksentrisk muskelarbeid og overvekt av forlenging av muskulatur i muskelarbeidet er mer effektiv enn en protokoll med konvensjonelle rehabiliteringsøvelser for å sikre en raskest mulig retur til idrett i svensk toppfotball.

#### Askling, 2014 [@askling2014]

En rehabiliteringsprotokoll med eksentrisk muskelarbeid og overvekt av forlenging av muskulatur i muskelarbeidet er mer effektiv enn en protokoll med konvensjonelle rehabiliteringsøvelser for å sikre en raskest mulig retur til idrett hos svenske friidrettsutøvere.

#### Hamid, 2014 [@ahamid2014]

En enkelt PRP injeksjon kombinert med et standard rehabiliteringsprogramm ga signifikant mer effektiv behandling av hamstringsskader enn standard rehabilitering alene.

#### Hamilton,2015 [@hamilton2015]

Det er ingen indikasjon på at det er tydelige fordeler ved en enkelt PRP-injeksjon sammenlignet med en intensiv rehabiliteringsprotokoll hos utøvere som har gjennomgått en akutt hamstringsskade.

## Referanser
