---
title: "Arbeidskrav_vitenskapsteori"
author: "Jacob Mollatt"
date: "11/28/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

1. Falsifikasjonisme
Poppers falsifiserbarhetskriterium dreier seg om differensieringen mellom vitenskapelige og uvitenskapelige teorier. Dette kriteriet går ut på at en teori må kunne falsifiseres for at den skal kunne betraktes som en vitenskapelig teori. På samme måte som teorier som ikke kunne falsifiseres da i den andre enden må betraktes som uvitenskapelige teorier(Karl R Popper, 1972). Det kan argumenteres for at et slikt kriterium løser demarkasjonsproblemet og gjør det mulig å unngå induksjonsproblemet i vitenskapsfilosofi, som det er mange meninger om(Karl R Popper, 1972; Vickers, 2006) 

Hovedproblemet som falsifiserbarhetskriteriumet gir svar på er nok allikevel demarkasjonsproblemet. Demarkasjonsproblemet baserer seg på utfordringen mellom å skille mellom vitenskapelige og uvitenskapelige teorier(Karl R Popper, 1972). Popper argumenterer for at det er tilstrekkelig å skille mellom en vitenskapelig og en uvitenskapelig teori, hvor på den andre siden Okasha og andre vitenskapsfilosofier argumenterer for at dette problemet ikke i seg selv er avgjørende å løse(Okasha, 2002). Grunnen til dette er at de mener det ikke finnes en tydelig avgrensning mellom hvilke teorier som kan betraktes som vitenskapelige og uvitenskapelige, og det på en annen side er viktigere å skille mellom teorier som har blitt bekreftet flere ganger, og teorier som ikke er bekreftet. De ønsker altså heller å skille mellom hvor godt og hvor dårlig en vitenskapelig teori er bekreftet, fremfor å dedikere avgrensningen til om noe er vitenskapelig eller uvitenskapelig(Karl R Popper, 1972; Okasha, 2002; Vickers, 2006) 

Sammen med å foreslå fasifiserbarhetskriteriumet som en løsning på demarkasjonsproblemet argumenterte Popper for at vi på denne måten også kan unngå induksjonsproblemet(Karl R Popper, 1972; Okasha, 2002; Vickers, 2006). Induksjonsproblemet dreier seg i motsetning til demarkasjonsproblemet mer om vitenskapelige argument. Det dreier seg i stor grad om det vil være mulig trekke slutninger om fremtiden basert på observasjoner vi gjør i dag(4. KvantMet2021 Vitenskapelige argument.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.; Vickers, 2006). Popper mente at alle vitenskapelige argument er deduksjoner som igjen falsifiserer en vitenskapelig teori. Gjennom deduksjon kan man derfor falsifisere en teori, før denne forkastes og erstattes med en ny. Kritikken rundt å bruke induksjon som vitenskapelige argument er derfor ikke lenger aktuell, ettersom man gjennom deduksjon og falsifikasjon enkelt kan unngå å bruke induksjon i vitenskapen(Karl R Popper, 1972). Der hvor andre vitenskapsfilosofer er opptatt av å bekrefte teorier, ønsket Popper heller å falsifisere og erstatte disse. Dette gjenspeiles videre i uenigheten omkring skillet mellom vitenskapelige og uvitenskapelige teorier, der spesielt Popper var opptatt av at det skulle være et markert skille påsto den andre leiren at det ikke finnes et særlig skarpt skille. Popper mente altså gjennom sin falsifikasjonisme at en vitenskapelig teori bare kunne bli falsifisert, mens andre vitenskapsfilosofer argumenterte for at den viktigste forskjellen lå i hvor godt eller dårlig bekreftet en teori var. 

2. HD-metoden og abduksjon
Strukturen på et bekreftende vitenskapelig argument er i følge den hypotetisk deduktive metoden slik at man legger opp deduktive argument fra teorien til dataen, gjennom å dedusere data fra teorien.(4. KvantMet2021 Vitenskapelige argument.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.). Man benytter teorien for å skape deduktive argumenter for hvordan dataen induktivt skal bekrefte teorien. Gjennom å dedusere data fra teorien vil det bety at teorien kan bekreftes. Men bare til en viss grad, dette er også grunnen til at mange derfor påstår at det bekreftende vitenskapelige argumentet faktisk er en induktiv bekreftelse snarere enn en deduktiv bekreftelse. 

I den hypotetisk deduktive metoden formuleres en teori eller en hypotese før det dannes empiriske konsekvenser fra disse(4. KvantMet2021 Vitenskapelige argument.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.; 5. KvantMet2021 Abduksjon og sannsynlighet.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.). Gjennom å gjenta observasjoner eller eksperimenter for å teste og undersøke de empiriske konsekvensene, vil man kunne oppnå en bekreftelse eller avkreftelse av hypotesen eller teorien(Hempel, Carl G, 1966). Denne prosessen mener Hempel er en induktiv prosess, ettersom det ved en induktiv bekreftelse av teorien gjennom observasjon av empiriske konsekvenser. Teorien er bekreftet til en viss grad. Derimot er konsekvensene vi tester deduktivt utledet fra teorien, og det er nettopp disse deduktive konsekvensene vi tester for å induktivt kunne bekrefte teorien eller hypotesen vi undersøker. 

Kort fortalt kan man den hypotetisk deduktive metoden beskrives på en måte der man ut ifra en idé eller teori sammenligner faktiske observasjoner med de forventede observasjonene teorien legger grunnlag for.

Hempel argumenterer for at gjennom å ta utgangspunkt i teorien, fremfor eksempelvis å ta utgangspunkt i observasjoner kunne utlede vitenskapelige argument på en mye mer effektiv måte(Hempel, Carl G, 1966). Kanskje spesielt sammenlignet med Bacons naive induktivisme(4. KvantMet2021 Vitenskapelige argument.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.) Sammenligner man Hempels hypotetisk deduktive metode med Poppers falsifikasjonisme, ser man en tydelig retning mot bekreftelse i Hempels metode, kontra avkreftelse i Poppers metode(Hempel, Carl G, 1966; Karl R Popper, 1972). Der Hempel ønsket å argumentere for, og å bekrefte ulike teorier i større eller mindre grad, ønsket popper å kunne skille tydelig mellom de vitenskapelige og ikke vitenskapelige teoriene, og helle falsifisere og argumentere mot teorier. 

Sammenligner man den hypotetisk deduktive metoden med abduksjon så er det mange likheter(4. KvantMet2021 Vitenskapelige argument.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.). I abduksjon vil man på samme måte som i den hypotetisk deduktive metoden ta utgangspunkt i en teori som man deretter danner grunnlag for å forklare forventede observasjoner, før man sammenligner de faktiske observasjonene med forventningen for å kunne gjøre en induktiv bekreftelse på teorien. I abduksjon forsøker man derimot i større grad å unngå deduksjon, noe som kan argumenteres for å være en utfordring i den hypotetisk deduktive metoden(5. KvantMet2021 Abduksjon og sannsynlighet.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.). Utfordringen ligger i argumentasjonen om at dataen og de forventede observasjonene man skal bruke til å induktivt bekrefte teorien ikke kan blir dedusert fra teorien. Her prøver heller abduksjonen å utlede empiriske konsekvenser induktiv fra teorien, for så å induktiv bekrefte teorien på nytt. Man angriper altså teorien og de empiriske konsekvensene på en noe mer logisk måte, gjennom å si at teorien vill gi en god forklaring på de relevante dataene vi sitter med, og at man velger den teorien som gir den mest logiske forklaringen på teorien. De empiriske konsekvensene man da danner, vil kunne observeres og etterprøves i eksperiment, for så å muligens kunne gi en induktiv bekreftelse av teorien og fortelle oss at teorien stemmer, til en viss grad. Der hvor den hypotetisk deduktive metoden låser seg til én enkelt hypotese, kan en i abduksjonen benytte seg av flere ulike teorier. De ulike teoriene kan sammenlignes så lenge de kan gi en forklaring på det samme fenomenet, og deretter vil man velger den teorien som gir den beste forklaringen på teorien(5. KvantMet2021 Abduksjon og sannsynlighet.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.). Abduksjonen vil for mange kunne oppleves som en større grad av subjektivitet, for hva er det egentlig som kan avgjøre om en teori gir en bedre forklaring på et fenomen enn ett annet, så lenge begge forklarer fenomenet? Videre kan abduksjonen fremstå som en mer effektiv vitenskapelig metode sammenlignet med den hypotetisk deduktive metoden, ettersom den hypotetisk deduktive metoden trolig dekker færre teorier enn hva abduksjon gjør. Til en viss grad kan det da argumenteres for at abduksjon som en vitenskapelig metode klarer å prøve ut flere teorier, og skille ut de som gir en dårligere forklaring på teorien, før man leter etter en måte å induktivt bekrefte denne teorien på. 

3. Replikasjonskrisen
Replikasjonskrisen i forskningen oppstår i forbindelse med at flere godt bekreftede eksperimentale resultater i ettertid blir motbevist og stilt spørsmålstegn ved etter at andre forskere har prøvd å replisere de orginale studiene(Bird, 2020). Flere og flere forskningsfunn blir argumentert for at det falske, eller feil analysert (Dalen-Lorentsen et al., 2020; Ioannidis, 2005). En vanlig forklaring bak replikasjonskrisen er ofte dårlig forskningskvalitet. Dårlig forskningspraksis, publikasjonsbias, dårlige insentiver og forskningsjuks(Fanelli, 2009; Joober et al., 2012). Bird forsøker å forklare og argumentere for hvorfor den høye andelen av mislykkede replikasjoner er samsvarende med god forskningspraksis og forskning på høyt nivå(Bird, 2020). Han argumenterer for at dette er et forventet utfall innen forskningsmiljøer som produserer en stor andel av falske hypoteser i forkant av testing. En slik fremgangsmåte vil føre til – sammen med en akseptert p-verdi og antatt insidens av type-1 feil på 5%. Disse tingene argumenterer han igjen at skyldes basefrekvensfeilen, og legger dette til grunn som en viktig årsak til den manglende evnen til å replisere studier innenfor spesielt sosialpsykologi og klinisk medisin(Bird, 2020).

Bird forklarer replikasjonskrisen gjennom at basefrekvensefeilen antakelig vil oppstå når man gjør en konklusjon ut fra observasjoner eller eksperiment som påvirkes av sannsynligheten for at en bestem hendelse av et generelt fenomen. Et slik generell fenomen kan for eksempel være om en gitt person i en gitt befolkning utvikler en bestemt form for sykdom eller ikke. Feilen Bird snakker om vil oppstår når man kun legger vekt på et enkelt bevis som skal forklare og underbygge hendelsen. Hvor vanlig eller hvor sjelden denne hendelsen er i utgangpsunktet, vil oftere neglisjeres, og man trekker derfor skjeve slutninger. Konklusjonene vil da ofte være at en faktor eller et bevis har en tydelig samvariasjon med undersøkelsene, men man glemmer at fenomenet i seg selv er veldig sjeldent. Eksempelvis når man undersøker styrken til en klinisk test, hvor sensitiviteten og spesifisiteten på en test blir målt til å være veldig god i de tilfellene hvor fenomenet faktisk oppstår, men når dette sammenlignes på populasjonsnivå så overser man sannsynligheten for at fenomenet oppstår i seg selv, og sannsynligheten for at testen faktisk vil finne det fenomenet eller resultatet som undersøkes påvirkes da i veldig stor grad(6. KvantMet2021 Sannsynlighet og replikasjonskrisen.pdf: IDR4000-1 21H Kvantitativ metode og statistikk, u.å.)

Selv om replikasjonskrisen trolig til en viss grad kan forklares av Birds argumenter, skal man ikke se langt tilbake i historien for å finne eksempler på andre forklaringer på krisen(Fanelli, 2009; Joober et al., 2012). Publikasjonsbias i seg selv har vært et emne som har fått mye oppmerksomhet de siste årene, samtidig som det er flere og flere eksempler på økende grad av artikler som trekkes tilbake på bakgrunn av nettopp bias, tvilsom forskningspraksis, juks eller svindel(Amos, 2014; Figure 2, u.å.). Økonomi og konkurranse mellom ulike forskningsinstitutt spiller trolig også inn, og man ser tidvis eksempler på dette også spesielt innen idrettsmedisin og idrettsvitenskap, der ofte ulike konkurrerende forskningsmiljøer ser ut til å ha en tendens til å gå etter hverandres forskning i sømmene(Dalen-Lorentsen et al., 2020; Hulin et al., 2016; Impellizzeri et al., 2021; van der Horst et al., 2014).
