---
title: "ARBEIDSKRAV 4"
author: "Jacob Mollatt"
date: "11-11-2021"
output:
  word_document:
    reference_docx: resources/template.docx
bibliography: resources/references.bib
csl: resources/vancouver.csl
---

# Studiedesign

## Formål

Forfatterne i samtlige studier inkludert i denne oppgaven ønsker å bidra til økt kunnskap som kan være med å løse den økende utfordringen med hamstringsskader i idretten, ettersom denne utfordringen har store konsekvenser for både prestasjon og økonomi [@ekstrand2011; @hickey2014; @eirale2013; @hickey2020; @askling2014; @hamilton2015; @ahamid2014; @askling2013]. Forfatterne ønsker å bidra til en økt kunnskap gjennom å formulere ulike spørsmål og sammenligningsgrunnlag. Alle studier har som formål å sammenligne to eller flere ulike rehabiliteringsprotokoller for å se hvilken av disse som har best effekt på tid til retur til idrett. Mer spesifikt ønsker tre av studiene å sammenligne hvilken effekt to ulike typer aktive rehabiliteringsprotokoller har på tiden det tar for å returnere til idrett etter en akutt hamstringsskade[@askling2014, @askling2013, @hickey2020]. De to andre studiene forsøker å se hvilken effekt injeksjoner av Platelet-Rich-Plasma (PRP)-<!-- PRP-injeksjon? definisjon Under finner jeg flere forkortelser som bør forklares for leseren --> har på rehabiliteringen av en hamstringsskade når det kombineres med aktiv rehabilitering, målt gjennom tid til retur til idrett[@ahamid2014; @hamilton2015].

Den røde tråden i disse artiklene finner vi igjen i utgangspunktet samtlige forfattere har i den tydelige byrden hamstringsskader har på prestasjon og økonomi i toppidretten[@ekstrand2011; @hickey2014; @eirale2013]. Videre vil kunnskapen vi allerede har, og dagens praksis omkring rehabiliteringen av hamstringsskader være med å påvirke retningen på disse studiene [@brooks2006; @horst2017; @opar2012; @podlog2014]. Økt kunnskap leder ofte til økt nysgjerrighet, og tiltak for å ytterlige optimalisere denne rehabiliteringsprosessen vil potensielt kunne gi tydelige fortrinn i toppidretten på flere ulike måter, hvor prestasjon og økonomi skiller seg ut som de to store.

## Metodisk sammenligning

Detaljert karakteristikk i metoden til de ulike studiene inkludert finnes i Tabell 1.

Alle de fem inkluderte artiklene er designet som randomiserte kontrollerte studier[@askling2014; @askling2013; @hickey2020; @ahamid2014; @hamilton2015].<!-- Beskriv denne studiedesignen nærmere, fordeler og ulemper? --> Deltakerne i studiene er hentet fra en populasjon av voksne idrettsutøvere med akutte hamstringsskader. Tretten ulike idretter er representert, med fotball og friidrett som de to største. Utvalgsstørrelsen varierte fra 24 til 90, med et snitt på 62 deltakere over de fem studiene. Totalt var det 308 deltakere, kjønnsfordelingen var omtrent 9% kvinner og 91% menn. To av studiene hadde kun mannlige deltakere [@hickey2020; @hamilton2015].Tre av studiene hadde på forhånd gjort en utregning av ønsket utvalgsstørrelse for en statistisk styrke på 80% [@hickey2020; @ahamid2014; @hamilton2015].<!-- Hvilke konsekvenser får dette for forskningsfeltet? --> Alle studiene sammenlignet ulike rehabiliteringsmetoder av akutte hamstringsskader opp mot hverandre med retur til idrett som utfallsmål, med mål om å finne forskjeller i utfallet av de ulike rehabiliteringsmetodene. Retur til idrett var definert ulikt i flere av studiene, og inklusjonskriteriene varierte også i stor grad mellom studiene. Dette gjør det vanskeligere å sammenligne studiene opp mot hverandre.

<!-- Du må bruke en tabellgenerator for å få tabellen formatert på en god måte. Alternativ kan du lage tabellen i Visual editor... -->

```{r eval=TRUE, echo=TRUE, warning=FALSE}
library(tidyverse)
library(readxl)
Tabell1 <- read_excel("resources/Tabell.xlsx")
View(Tabell1)
```

`r View(Tabell1)`

**Studiekarakteristikk**

+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Forfatter** | **Utvalgstørrelse**                                           | **Rekruttering**                                                                     | **Statistisk power**                                                          | **Intervensjoner**                                                           | **Utfallsmål**                                                                | **Statistiske tester**                                                       |
+===============+===============================================================+======================================================================================+===============================================================================+==============================================================================+===============================================================================+==============================================================================+
| Hickey,       | 45                                                            | Rekruttering skjedde løpende                                                         | 29 deltakere var ønsket for                                                   | Progressiv stegvis                                                           | Tid til retur. Tid fra                                                        | Intention-to-treat                                                           |
| 2020          | menn med akutt HSI\* \<7 dager.                               | over en periode på 15mnd. Potensielle deltakere ble rekruttering via                 | statistisk styrke på 80%, medregnet en drop-out på 20%. Basert på en          | rehabiliterings-protokoll bestående av øvelser for å styrke                  | skade-tidspunkt til kriterier for retur til idrett var bestått.               | analyse ble brukt til å undersøke protokollens effekt på antall dager til    |
|               |                                                               | reklameplakater og kontakt med lokale idrettslag og klinikker. Deltakere ble         | effektstørrelse på 1,2.                                                       | hamstring-muskulatur og løping. Progresjon og gjennomføring innenfor         |                                                                               | retur til idrett, og antallet re-skader, gjennom å bruke en                  |
|               |                                                               | til slutt inkludert på bakgrunn av forhåndsdefinerte inklusjonskriterier.            |                                                                               | smertefrihet. 0 på NRS\*\*                                                   |                                                                               | Cox--regresjonsmodell.Kaplan-Meier metode ble brukt for å sammenligne        |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | kumulativ survival rate med tid til retur til idrett. (survival package i R, |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | versjon 3.4.3)                                                               |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               | Progressiv stegvis rehabiliterings-protokoll                                 |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | bestående av øvelser for å styrke hamstring-muskulatur og løping. Progresjon |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | og gjennomføring innenfor en gitt smertegrense \<4 på NRS\*\*.               |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| Askling,      | 75                                                            | Rekrutteringen skjedde over en                                                       | Ikke definert                                                                 | Rehabiliterings-protokoll                                                    | Tid til retur. Tid fra                                                        | Shapiro-Wilk                                                                 |
| 2013          | fotballspillere med akutt HSI\* \<2 dager.                    | løpende periode på 33 måneder. Gjennom forfatternes idrettmedisinske                 |                                                                               | bestående av 3 øvelser med fokus på å styrke hamstringen i hovedsak med      | skade-tidspunkt til full deltakelse i lagstrening og tilgjengelighet for      | W test ble brukt til å undersøke om data var normalfordelt, noe de viste seg |
|               |                                                               | kontaktnettverk innen svensk fotball. Deltakere ble til slutt inkludert på           |                                                                               | eksentrisk muskelarbeid (L-protokoll).                                       | kamp.                                                                         | å ikke være. Mann-Withney U test ble brukt til å undersøke forskjeller i     |
|               |                                                               | bakgrunn av forhåndsdefinerte inklusjonskriterier.                                   |                                                                               |                                                                              |                                                                               | deskriptive data, men også til å undersøke forskjell i tid til retur til     |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | idrett mellom protokollene. Forfatterne brukte også Spearman Rank order      |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | correlations for å undersøke hvilken korrelasjon som fantes mellom tid til   |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | retur til idrett, MR-funn og kliniske funn.                                  |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               | Rehabiliterings-protokoll                                                    |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | bestående av 3 øvelser med fokus på å styrke hamstringen (C-protokoll).      |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| Askling,      | 57                                                            | Rekrutteringen skjedde over en                                                       | Ikke definert                                                                 | Rehabiliterings-protokoll                                                    | Tid til retur. Tid fra                                                        | Shapiro-Wilk                                                                 |
| 2014          | elite friidrettsutøvere med akutt HSI\* \<2 dager.            | løpende periode på 38 måneder. Gjennom forfatternes idrettmedisinske                 |                                                                               | bestående av 3 øvelser med fokus på å styrke hamstringen i hovedsak med      | skade-tidspunkt til full deltakelse i trening.                                | W test ble brukt til å undersøke om data var normalfordelt, noe de viste seg |
|               |                                                               | kontaktnettverk innen svensk friidrett, og invitasjoner ble også sendt ut            |                                                                               | eksentrisk muskelarbeid (L-protokoll).                                       |                                                                               | å ikke være. Mann-Withney U test ble brukt til å undersøke forskjeller i     |
|               |                                                               | gjennom det svenske friidrettsforbundet. Deltakere ble til slutt inkludert på        |                                                                               |                                                                              |                                                                               | deskriptive data, men også til å undersøke forskjell i tid til retur til     |
|               |                                                               | bakgrunn av forhåndsdefinerte inklusjonskriterier.                                   |                                                                               |                                                                              |                                                                               | idrett mellom protokollene. Forfatterne brukte også Spearman Rank order      |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | correlations for å undersøke hvilken korrelasjon som fantes mellom tid til   |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | retur til idrett, MR-funn og kliniske funn.                                  |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               | Rehabiliterings-protokoll                                                    |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | bestående av 3 øvelser med fokus på å styrke hamstringen (C-protokoll).      |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| Hamid,        | 24                                                            | Pasienter over 18 år som                                                             | 28 deltakere(14 i hver                                                        | Rehabiliterings-protokoll for å                                              | Tid til retur. Tid fra                                                        | Kaplan-Meier                                                                 |
| 2014          | Ikke-profesjonelle utøvere med akutt HSI\* \<7 dager          | oppsøkte den Idrettsmedisinske klinikken på UMMC med mistenkt hamstringsskade        | intervensjons-gruppe) var ønsket for statistisk styrke på 80% med             | styrke hamstring samt progressiv agilitytrening og styrke av                 | skade-tidspunkt til kriterier for retur til idrett var oppfylt. Målt ukentlig | metode ble brukt for å sammenligne kumulativ survival rate med tid til retur |
|               |                                                               | ble undersøkt og inkludert etter diagnose og på bakgrunn og forhåndsdefinerte        | signifikansnivå satt til 0,05.                                                | kjernemuskulatur. Samt injeksjon av PRP\*\*\*.                               | eller til studien avsluttet ble avsluttet(16 uker).                           | til idrett. Cox regresjonsanalyse for å evaluere effekt av intervensjon og   |
|               |                                                               | inklusjonskriterier.                                                                 |                                                                               |                                                                              |                                                                               | andre covariater på tid til retur.                                           |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               | Rehabiliterings-protokoll for å                                              |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | styrke hamstring samt progressiv agilitytrening og styrke av                 |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | kjernemuskulatur.                                                            |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| Hamilton,     | 90                                                            | Pasienter ble rekruttert fra                                                         | 60 deltakere var ønsket for                                                   | Rehabiliterings-protokoll for å                                              | Tid til retur. Tid fra                                                        | Pearson                                                                      |
| 2015          | Idrettsutøvere henvist til ASPETAR med akutt HSI\* \<5 dager. | klubber og forbund tilknyttet et nasjonalt idrettsmedisinsk program i Qatar.         | statistisk styrke på 80% med signifikansnivå på 0,05 medregnet en drop-out på | styrke hamstring (usual care), samt injeksjon av PRP\*\*\*                   | skade-tidspunkt til gjennomført rehabilitering og kriterier for retur til     | Chi-squared test på kategoriske data og one-way ANOVA mellom gruppene med    |
|               |                                                               | Medisinsk støtteapparat henviste til studiesenteret ved mistanke om en akutt         | 10%.                                                                          |                                                                              | idrett var oppfylt.                                                           | konktinuerlige data. Kaplan-Meier metode ble brukt for å sammenligne         |
|               |                                                               | HSI. Deltakerne ble inkludert på bakgrunn av forhåndsdefinerte inklusjonskriterier.  |                                                                               |                                                                              |                                                                               | kumulativ survival rate med tid til retur til idrett. Cox -regresjonsmodell  |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | og linære regresjonsmodeller ble brukt for å se på effekt av intervensjon på |
|               |                                                               |                                                                                      |                                                                               |                                                                              |                                                                               | tid til retur til idrett.                                                    |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               | Rehabiliterings-protokoll for å                                              |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | styrke hamstring (usual care), samt injeksjon av                             |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | placebo-sammenligner(PPP\*\*\*\*)                                            |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+
|               |                                                               |                                                                                      |                                                                               | Rehabiliterings-protokoll for å                                              |                                                                               |                                                                              |
|               |                                                               |                                                                                      |                                                                               | styrke hamstring (usual care),                                               |                                                                               |                                                                              |
+---------------+---------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------------------------------------------------------------------------+

: *\*Hamstring strain injury - hamstringsskade\
\*\*Numerical Rating Scale**\
***\*\*\*Platelet-Rich-Plasma\
\*\*\*\*Platelet-Poor-Plasma\

## Resultater

I studiene som sammenlignet to ulike aktive rehabiliteringsprotokoller fant to av studiene signifikante forskjeller i tid til retur til idrett [@askling2013, @askling2014]. Den tredje av studiene fant ingen signifikant forskjell i tid til retur til idrett[@hickey2020]. Blant de to studiene som undersøkte effekten av en PRP injeksjon, fant den ene studien en signifikant kortere tid til retur til idrett i gruppen med PRP injeksjon og standard rehabilitering, sammenlignet med gruppen som kun gjennomgikk standard rehabilitering[@ahamid2014]. Den andre studien fant ingen signifikant forskjell i tiden til retur til idrett mellom gruppen som mottok PRP-injeksjon og gruppen som mottok en standard rehabilitering[@hamilton2015]. Resultatene er oppsummert fordelt på studiene under.

#### Hickey, 2020 [@hickey2020]

Ingen signifikant forskjell i hovedutfallsmål, som var tid til retur til idrett. Sekundære utfallsmål på isometrisk knefleksjon og fasikkellengde i biceps femoris caput longum var bedre i gruppen med rehabilitering innenfor smertegrense 4 på Numerical Rating Scale(NRS). Median tid fra skade til retur til idrett var 15 dager(95% konfidensintervall) i gruppen med smertefrihet, og 17 dager(95% konfidensintervall) i gruppen med smertegrense på 4 på NRS. P-verdi på 0.37.

#### Askling, 2013 [@askling2013]

Signifikant kortere rehabilitering i gruppen med eksentrisk muskelarbeid og forlenging av muskulatur(L-protokoll) sammenlignet med den andre konvensjonelle rehabiliteringsgruppen(C-protokoll)(p\<0.001). Gjennomsnittlig tid til til retur til idrett i L-protokoll var 28 dager (1SD±15, range 8--58 dager), sammenlignet med et snitt på 51 dager (1SD±21, range 12--94 dager) i C-protokoll.

#### Askling, 2014 [@askling2014]

Signifikant kortere rehabilitering i gruppen med eksentrisk muskelarbeid og forlenging av muskulatur(L-protokoll) sammenlignet med den andre konvensjonelle rehabiliteringsgruppen(C-protokoll)(p\<0.001, d=−1.21). Gjennomsnittlig tid til retur til idrett i L-protokoll var 49 dager (1SD±26, range 18--107 dager), sammenlignet med et snitt på 86 dager (1SD±34, range 26--140 dager) i C-protokoll.

#### Hamid, 2014 [@ahamid2014]

Pasientene som mottok PRP injeksjon sammen med rehabiliteringsprogrammet hadde en signifikant tidligere retur til idrett sammenlignet med de som ikke mottok PRP-injeksjon(p = 0.02). Gjennomsnittlig tid til retur var 42.5 +- 20.6 dager i kontrollgrupen, og 26.7+.- 7 dager i PRP gruppen.

#### Hamilton,2015 [@hamilton2015]

Justert differanse i tid til retur til idrett mellom PRP-gruppen og PPP-gruppen var −5.7 dager (95% CI, p=0.01). Mellom PRP og kontrollgruppen −2.9 dager (95% CI, p=0.189) og mellom PPP og kontrollgruppen 2.8 dager (95% CI, p=0.210).

## Konklusjoner

Tre av studiene konkluderte med at de fant en forskjell i effekten de ulike intervensjonene de undersøkte hadde på tid til retur til idrett[@askling2013; @askling2014; @ahamid2014]. To av disse studiene konkluderte med at en rehabiliteringsprotokoll med eksentrisk muskelarbeid og overvekt av forlenging av muskulatur i muskelarbeidet er mer effektivt en konvensjonelle rehabiliteringsøvelser[@askling2013, @askling2014]. Den siste studien konkluderte med at en PRP-injeksjon kombinert med standard rehabilitering hadde større positiv effekt på tid til retur til idrett enn en standard rehabilitering alene[@ahamid2014]. De to siste studiene konkluderte med at det ikke var noen forskjell i effekten de ulike intervensjonene de undersøkte hadde på tid til retur til idrett[@hickey2020, @hamilton2015]. To av studiene inkludert kom til motsvarende konklusjoner, der den ene konkluderte med at en enkelt PRP-injeksjon ikke hadde effekt på tid til retur til idrett, mens den andre konkluderte med at en enkelt PRP-injeksjon hadde positiv effekt på tid til retur til idrett[@hamilton2015, @ahamid2014]. Konklusjoner er oppsummert og fordelt på de ulike studiene under.

#### Hickey, 2020 [@hickey2020]

Rehabilitering innenfor smertegrense på 4 på NRS ga ingen raskere retur til idrett enn rehabilitering innenfor smertefrihet, men bedret andre utfallsmål som isometrisk styrke i knefleksjon og fasikkellengde.

#### Askling, 2013 [@askling2013]

En rehabiliteringsprotokoll med eksentrisk muskelarbeid og overvekt av forlenging av muskulatur i muskelarbeidet er mer effektiv enn en protokoll med konvensjonelle rehabiliteringsøvelser for å sikre en raskest mulig retur til idrett i svensk toppfotball.

#### Askling, 2014 [@askling2014]

En rehabiliteringsprotokoll med eksentrisk muskelarbeid og overvekt av forlenging av muskulatur i muskelarbeidet er mer effektiv enn en protokoll med konvensjonelle rehabiliteringsøvelser for å sikre en raskest mulig retur til idrett hos svenske friidrettsutøvere.

#### Hamid, 2014 [@ahamid2014]

En enkelt PRP injeksjon kombinert med et standard rehabiliteringsprogramm ga signifikant mer effektiv behandling av hamstringsskader enn standard rehabilitering alene.

#### Hamilton,2015 [@hamilton2015]

Det er ingen indikasjon på at det er tydelige fordeler ved en enkelt PRP-injeksjon sammenlignet med en intensiv rehabiliteringsprotokoll hos utøvere som har gjennomgått en akutt hamstringsskade.

## Referanser
